from pathlib import Path
import sys, zlib, base64, json

root = Path(sys.argv[1] if len(sys.argv) > 1 else 'fluentx_admin_secure')
assets = Path(__file__).resolve().parent / 'payloads'


def decode_payload(name: str) -> bytes:
    raw = (assets / name).read_text().strip()
    return zlib.decompress(base64.b64decode(raw))


def write_bytes(rel: str, data: bytes) -> None:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    print(f'Applied {rel}')

# Full 60-week personalized path + placement/adaptive recommendation backend.
write_bytes(
    'supabase/migrations/0012_personalized_learning_path.sql',
    decode_payload('0012_personalized_learning_path.b64'),
)

# Gemini-backed server functions. No Gemini key is embedded in the app/source.
write_bytes('supabase/functions/score-writing/index.ts', decode_payload('score-writing.b64'))
write_bytes('supabase/functions/ai-practice-chat/index.ts', decode_payload('ai-practice-chat.b64'))
write_bytes('supabase/functions/score-placement-speaking/index.ts', decode_payload('score-placement-speaking.b64'))

# Build the market-ready seed migration from compact compressed structured data.
content_blob = ''.join((assets / f'content_data_{i}.b64').read_text().strip() for i in range(1, 5))
data = json.loads(zlib.decompress(base64.b64decode(content_blob)).decode('utf-8'))


def q(value):
    if value is None:
        return 'NULL'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def text_array(values):
    return 'ARRAY[' + ','.join(q(x) for x in values) + ']::text[]'

sql = [
    '-- FluentX market-ready content pack generated by CI.',
    '-- Idempotent: existing natural-key rows are preserved.',
    'BEGIN;',
]

for word, definition, example, category in data['v']:
    sql.append(
        f"INSERT INTO public.vocabulary_words (word, definition, example_sentence, category) "
        f"SELECT {q(word)}, {q(definition)}, {q(example)}, {q(category)} "
        f"WHERE NOT EXISTS (SELECT 1 FROM public.vocabulary_words WHERE lower(word)=lower({q(word)}) AND category={q(category)});"
    )

for title, explanation, category, order_index in data['gl']:
    sql.append(
        f"INSERT INTO public.grammar_lessons (title, explanation, category, order_index) "
        f"SELECT {q(title)}, {q(explanation)}, {q(category)}, {order_index} "
        f"WHERE NOT EXISTS (SELECT 1 FROM public.grammar_lessons WHERE title={q(title)});"
    )
for question, options, correct_index, title in data['gq']:
    sql.append(
        f"INSERT INTO public.grammar_questions (lesson_id, question_text, options, correct_index) "
        f"SELECT l.id, {q(question)}, {text_array(options)}, {correct_index} FROM public.grammar_lessons l "
        f"WHERE l.title={q(title)} AND NOT EXISTS (SELECT 1 FROM public.grammar_questions q WHERE q.question_text={q(question)});"
    )

for title, category, transcript in data['lc']:
    sql.append(
        f"INSERT INTO public.listening_clips (title, category, transcript) "
        f"SELECT {q(title)}, {q(category)}, {q(transcript)} "
        f"WHERE NOT EXISTS (SELECT 1 FROM public.listening_clips WHERE title={q(title)});"
    )
for question, options, correct_index, title in data['lq']:
    sql.append(
        f"INSERT INTO public.listening_questions (clip_id, question_text, options, correct_index) "
        f"SELECT c.id, {q(question)}, {text_array(options)}, {correct_index} FROM public.listening_clips c "
        f"WHERE c.title={q(title)} AND NOT EXISTS (SELECT 1 FROM public.listening_questions q WHERE q.question_text={q(question)});"
    )

for title, category, instructions in data['w']:
    sql.append(
        f"INSERT INTO public.writing_prompts (title, category, instructions) "
        f"SELECT {q(title)}, {q(category)}, {q(instructions)} "
        f"WHERE NOT EXISTS (SELECT 1 FROM public.writing_prompts WHERE title={q(title)});"
    )

for title, category, description, system_prompt in data['a']:
    sql.append(
        f"INSERT INTO public.ai_practice_scenarios (title, category, description, system_prompt) "
        f"SELECT {q(title)}, {q(category)}, {q(description)}, {q(system_prompt)} "
        f"WHERE NOT EXISTS (SELECT 1 FROM public.ai_practice_scenarios WHERE title={q(title)});"
    )

sql += ['COMMIT;', '']
write_bytes('supabase/migrations/0013_market_ready_content.sql', '\n'.join(sql).encode('utf-8'))

# Honest, market-safe module labels: never advertise inventory counts the DB does not yet prove.
learn = root / 'lib/features/learn/presentation/screens/learn_hub_screen.dart'
if learn.exists():
    text = learn.read_text()
    replacements = {
        '10,000+ words': 'Smart spaced-repetition vocabulary',
        '100+ lessons': 'Practical grammar lessons & quizzes',
        'Real-world audio clips': 'Real-world listening practice',
        'AI-powered feedback': 'Personalized AI writing feedback',
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    learn.write_text(text)
    print('Updated Learn module claims.')

# Clear AI disclosure on writing score output.
writing = root / 'lib/features/writing/presentation/widgets/writing_editor_sheet.dart'
if writing.exists():
    text = writing.read_text()
    marker = "Text('AI Feedback', style: Theme.of(context).textTheme.headlineSmall),\n        const SizedBox(height: AppSpacing.base),"
    insert = "Text('AI Feedback', style: Theme.of(context).textTheme.headlineSmall),\n        const SizedBox(height: AppSpacing.xs),\n        Text(\n          'AI-generated learning feedback. Review important communication before relying on it.',\n          style: Theme.of(context).textTheme.bodySmall?.copyWith(color: colorScheme.onSurfaceVariant),\n        ),\n        const SizedBox(height: AppSpacing.base),"
    if marker in text:
        text = text.replace(marker, insert, 1)
    writing.write_text(text)
    print('Added Writing AI disclosure.')

# Clear AI disclosure on conversation-session summary.
summary = root / 'lib/features/ai_practice/presentation/widgets/practice_summary_view.dart'
if summary.exists():
    text = summary.read_text()
    marker = "Text('Session Summary', style: Theme.of(context).textTheme.displayLarge),\n          const SizedBox(height: AppSpacing.lg),"
    insert = "Text('Session Summary', style: Theme.of(context).textTheme.displayLarge),\n          const SizedBox(height: AppSpacing.xs),\n          Text(\n            'AI-generated coaching based on this practice session.',\n            style: Theme.of(context).textTheme.bodySmall?.copyWith(color: colorScheme.onSurfaceVariant),\n          ),\n          const SizedBox(height: AppSpacing.lg),"
    if marker in text:
        text = text.replace(marker, insert, 1)
    summary.write_text(text)
    print('Added AI Practice disclosure.')

print('FluentX market-ready completion patch applied.')
